export const statusConfig = {
  all: {
    color: "text-gray-700",  // Màu chữ khi không active
    iconColor: "text-gray-600",
    icon: null,
    label: "Tất cả đơn hàng",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-300",
    activeBgColor: "bg-gray-100",  // Màu nền khi active
    activeTextColor: "text-gray-800",  // Màu chữ khi active
    activeBorderColor: "border-l-4 border-gray-600",  // Viền trái khi active
  },
  Draft: {
    color: "text-amber-700",
    iconColor: "text-amber-600",
    icon: null,
    label: "Nháp",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-400",
    activeBgColor: "bg-amber-100",
    activeTextColor: "text-amber-800", 
    activeBorderColor: "border-l-4 border-amber-600",
  },
  Processing: {
    color: "text-purple-700",
    iconColor: "text-purple-600",
    icon: null,
    label: "Đang xử lý",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-400",
    activeBgColor: "bg-purple-100",
    activeTextColor: "text-purple-800",
    activeBorderColor: "border-l-4 border-purple-600",
  },
  PendingPayment: {
    color: "text-orange-700",
    iconColor: "text-orange-600",
    icon: null,
    label: "Chờ thanh toán",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-400",
    activeBgColor: "bg-orange-100",
    activeTextColor: "text-orange-800",
    activeBorderColor: "border-l-4 border-orange-600",
  },
  Paid: {
    color: "text-blue-700",
    iconColor: "text-blue-600",
    icon: null,
    label: "Đã thanh toán",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-400",
    activeBgColor: "bg-blue-100",
    activeTextColor: "text-blue-800",
    activeBorderColor: "border-l-4 border-blue-600",
  },
  Completed: {
    color: "text-emerald-700",
    iconColor: "text-emerald-600",
    icon: null,
    label: "Hoàn thành",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-400",
    activeBgColor: "bg-emerald-100",
    activeTextColor: "text-emerald-800",
    activeBorderColor: "border-l-4 border-emerald-600",
  },
  Canceled: {
    color: "text-rose-700",
    iconColor: "text-rose-600",
    icon: null,
    label: "Đã hủy",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-400",
    activeBgColor: "bg-rose-100",
    activeTextColor: "text-rose-800",
    activeBorderColor: "border-l-4 border-rose-600",
  }
};
